name: Make and push loader patch

on:
  schedule: 
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Make Loader patch
        run: |
          pip install lz4
          python3 loader_patch.py

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: Atmosphere-NX/Atmosphere
          path: Atmosphere

      - name: Add Loader patch to git
        run: bash loader_patch.sh >/dev/null 2>&1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}