name: Make and push loader patch

on:
  schedule: 
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  sigpatches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: SigPatches

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip3 install lz4

      - name: Make Loader patch
        run: cd SigPatches && python3 scripts/loader_patch.py

      - name: push changes
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd SigPatches && \
          git config --global advice.detachedHead false && \
          git config --global user.name 'borntohonk' && \
          git config --global user.email '6264306+borntohonk@users.noreply.github.com' && \
          HASH=$(gh release view --repo github.com/Atmosphere-NX/Atmosphere --json assets --jq .assets[].url | grep -oE "\-([0-9a-f]{9})" | head -1 | cut -c2-)
          git clone https://github.com/Atmosphere-NX/Atmosphere.git ../Atmosphere && \
          sleep 5 && \
          git -C ../Atmosphere checkout $HASH && \
          AMSMAJORVER=$(grep 'define ATMOSPHERE_RELEASE_VERSION_MAJOR\b' ../Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
          AMSMINORVER=$(grep 'define ATMOSPHERE_RELEASE_VERSION_MINOR\b' ../Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
          AMSMICROVER=$(grep 'define ATMOSPHERE_RELEASE_VERSION_MICRO\b' ../Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
          HOS_MAJORVER=$(grep 'define ATMOSPHERE_SUPPORTED_HOS_VERSION_MAJOR\b' ../Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
          HOS_MINORVER=$(grep 'define ATMOSPHERE_SUPPORTED_HOS_VERSION_MINOR\b' ../Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
          HOS_MICROVER=$(grep 'define ATMOSPHERE_SUPPORTED_HOS_VERSION_MICRO\b' ../Atmosphere/libraries/libvapours/include/vapours/ams/ams_api_version.h | tr -s [:blank:] | cut -d' ' -f3)
          HOSVER=$HOS_MAJORVER.$HOS_MINORVER.$HOS_MICROVER
          AMSVER=$AMSMAJORVER.$AMSMINORVER.$AMSMICROVER
          sleep 1
          git fetch
          sleep 1
          git add hekate_patches
          sleep 1
          git add SigPatches/atmosphere
          sleep 1
          if [[ `git status --porcelain` ]]; then
            git commit -m"Loader patch for $HASH was added!" && \
            git push && \
            sleep 1 && \
            echo "" > changelog.md && \
            echo "- es, fs and nifm patches for HOS ${HOSVER} are included" >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- has loader patches for Atmosphere version ${AMSVER}-${HASH}" >> changelog.md && \
            echo "" >> changelog.md && \
            echo "- Hekate style patches are included for both loader and FS" >> changelog.md && \
            echo "" >> changelog.md && \
            sleep 5 && \
            gh release create $HOSVER-$AMSVER-$HASH -F changelog.md SigPatches.zip --title "Supports HOS firmware $HOSVER and AMS $AMSVER-$HASH" --repo github.com/borntohonk/SigPatches && \
            sleep 5 && \
            rm -rf ../Atmosphere && \
            rm changelog.md && \
            rm SigPatches.zip
          else
            echo "No new patches were generated" && \
            rm -rf ../Atmosphere && \
            exit
          fi