name: Make and push loader patch

on:
  schedule: 
    - cron:  '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: borntohonk/suppository:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Loader patch
        run: python3 loader_patch.py

      - name: Add Loader patch to git
        run: bash loader_patch.sh
          